### ISSUE TITLE
Dashboard timeout length

### ISSUE THREAD

**Issue by janash** [molssi-seamm/seamm_dashboard#76]
The dashboard currently will log out the user after not being accessed for 20 minutes. @paulsaxe has suggested that we increase this time to much longer, perhaps a number of hours (2 hours, maybe)?

Any thoughts, @paulsaxe ?

**Comment by paulsaxe** [comment]
I have upped it to 10 hours in my version -- which I think is reasonable for most uses. Ideally we would make it an option that the user could set, for the time being can procrastinate if that would be considerable work. If easy, however, it would be the best solution.
